runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
env_variables:
  'ENDPOINTS_SERVICE_NAME': 'sobike44.appspot.com'
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.js)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.html)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /prefixquery
  script: unused
  login: optional
  secure: optional
- url: /friends
  script: unused
  login: optional
  secure: optional
- url: /MsgIndex
  script: unused
  login: optional
  secure: optional
- url: /prefixclean
  script: unused
  login: optional
  secure: optional
- url: /counttr
  script: unused
  login: optional
  secure: optional
- url: /query
  script: unused
  login: optional
  secure: optional
- url: /count
  script: unused
  login: optional
  secure: optional
- url: /userapi
  script: unused
  login: optional
  secure: optional
- url: /hello
  script: unused
  login: optional
  secure: optional
- url: /fb
  script: unused
  login: optional
  secure: optional
- url: /pquery
  script: unused
  login: optional
  secure: optional
- url: /petition
  script: unused
  login: optional
  secure: optional
- url: /prefix
  script: unused
  login: optional
  secure: optional
- url: /TestTransaction
  script: unused
  login: optional
  secure: optional
- url: /onetuple
  script: unused
  login: optional
  secure: optional
- url: /countsh
  script: unused
  login: optional
  secure: optional
- url: /Consistency
  script: unused
  login: optional
  secure: optional
- url: /thecount
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
